name: Build & Deploy BE to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/be-appservice.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -q -DskipTests clean package

      # نرفع ملف الـ JAR الناتج إلى الويب آب
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: alyazidi-be          # <- اسم Web App للباك إند
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BE }}
          package: backend/target/*.jar
