name: Build & Push Docker images

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/docker-ci.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Frontend
      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: alyzedi/my-frontend:latest

      # Backend
      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: alyzedi/my-backend:latest
